name: IQ Server Scan - Full Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iq_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java (necessário para o IQ Server)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Rodar scan do IQ Server enviando todos os arquivos do repositório
      - name: Run IQ Server scasn
        run: |
          curl -u "${{ secrets.IQ_USER }}:${{ secrets.IQ_PASSWORD }}" \
               -F "applicationId=${{ secrets.IQ_APPLICATION_ID }}" \
               -F "scan=@." \
               "${{ secrets.IQ_SERVER_URL }}/api/v2/scan/applications/${{ secrets.IQ_APPLICATION_ID }}/sources"
