name: IQ Server Scan - Full Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iq_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java (requerido pelo IQ Server)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Compactar o código-fonte do repositório
      - name: Compactar repositório
        run: zip -r source.zip .

      # 4️⃣ Testar autenticação com o IQ Server (verificar se o token/user funciona)
      - name: Testar conexão com IQ Server
        env:
          IQ_USER: ${{ secrets.IQ_USER }}
          IQ_PASSWORD: ${{ secrets.IQ_PASSWORD }}
        run: |
          echo "🔹 Testando autenticação com o Sonatype IQ Server..."
          curl -v -u "$IQ_USER:$IQ_PASSWORD" \
               "https://hairlike-cami-fiercely.ngrok-free.dev/api/v2/organizations"

      # 5️⃣ Enviar código para o IQ Server e rodar o SCA
      - name: Executar SCA no IQ Server
        env:
          IQ_USER: ${{ secrets.IQ_USER }}
          IQ_PASSWORD: ${{ secrets.IQ_PASSWORD }}
          IQ_APPLICATION_ID: ${{ secrets.IQ_APPLICATION_ID }}
        run: |
          echo "🚀 Enviando código-fonte para análise no IQ Server..."
          curl -v -u "$IQ_USER:$IQ_PASSWORD" \
               -F "applicationId=$IQ_APPLICATION_ID" \
               -F "scan=@source.zip" \
               "https://hairlike-cami-fiercely.ngrok-free.dev/api/v2/scan/applications/$IQ_APPLICATION_ID/sources"
