name: IQ Server Scan - Full Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iq_scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java (requerido pelo IQ Server)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Compactar o código-fonte do repositório
      - name: Compactar repositório
        run: zip -r source.zip .

      # 4️⃣ Testar autenticação com o IQ Server
      - name: Testar conexão com IQ Server
        run: |
          echo "🔹 Testando autenticação com o Sonatype IQ Server..."
          curl -v -u "VJA9wEh4:ycKAOghFvmpQdzNLvoIwj3xRvsp08zQtMUBrBJAiqjBK" \
               "https://hairlike-cami-fiercely.ngrok-free.dev/api/v2/organizations"

      # 5️⃣ Enviar código para o IQ Server e rodar o SCA
      - name: Executar SCA no IQ Server
        run: |
          echo "🚀 Enviando código-fonte para análise no IQ Server..."
          curl -v -u "VJA9wEh4:ycKAOghFvmpQdzNLvoIwj3xRvsp08zQtMUBrBJAiqjBK" \
               -F "applicationId=z5nf6bxw" \
               -F "scan=@source.zip" \
               "https://hairlike-cami-fiercely.ngrok-free.dev/api/v2/scan/applications/z5nf6bxw/sources"
